# Training configuration
GPU: [0,1,2,3]

VERBOSE: False

MODEL:
  MODE: 'SRMNet_denoise'

# Optimization arguments.
OPTIM:
  BATCH: 2
  EPOCHS: 100
  # EPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: 'D:/PycharmProjects/SUNet-main/datasets/Denoising_DIV2K/train'       # path to training data
  VAL_DIR: 'D:/PycharmProjects/SUNet-main/datasets/Denoising_DIV2K/test' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
